[package]
authors = ["The Rust Project Developers"]
name = "flate"
version = "0.0.0"
build = "build.rs"

[lib]
name = "flate"
path = "lib.rs"

[build-dependencies]
build_helper = { path = "../build_helper" }
gcc = "0.3.50"
