[package]
authors = ["The Rust Project Developers"]
name = "test"
version = "0.0.0"

[lib]
name = "test"
path = "lib.rs"

[dependencies]
getopts = { path = "../libgetopts" }
term = { path = "../libterm" }
